name: master-thesis-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.11.11
  - cycler=0.11.0
  - debugpy=1.8.13
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fonttools=4.55.3
  - freetype=2.12.1
  - fuzzywuzzy=0.18.0
  - hdbscan=0.8.39
  - icc_rt=2022.1.0
  - icu=73.1
  - imbalanced-learn=0.13.0
  - importlib-metadata=8.6.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.0.2
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxgboost=2.1.1
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numexpr=2.10.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.5.0
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - pure_eval=0.2.3
  - py-xgboost=2.1.1
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-levenshtein=0.12.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2024.1
  - pywin32=307
  - pyzmq=26.2.0
  - qtbase=6.7.2
  - qtdeclarative=6.7.2
  - qtsvg=6.7.2
  - qttools=6.7.2
  - qtwebchannel=6.7.2
  - qtwebsockets=6.7.2
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - seaborn=0.13.2
  - setuptools=75.8.0
  - sip=6.10.0
  - six=1.16.0
  - sklearn-compat=0.1.3
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xgboost=2.1.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - attrs==25.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - cleanlab==2.7.1
      - datasets==3.5.0
      - dill==0.3.8
      - filelock==3.18.0
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - huggingface-hub==0.30.1
      - idna==3.10
      - multidict==6.3.1
      - multiprocess==0.70.16
      - numpy==1.26.4
      - propcache==0.3.1
      - pyarrow==19.0.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - scikit-clean==0.1.2
      - termcolor==3.0.1
      - urllib3==2.3.0
      - xxhash==3.5.0
      - yarl==1.18.3
